version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/London
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/London
